global:
  scrape_interval: 2s
scrape_configs:
#  - job_name: prometheus
#    static_configs:
#     - targets:
#        - prometheus:9090
       
 - job_name: mysql_exporter
   static_configs:
    - targets:
       - mysqld-exporter:9104
